####
POST http://localhost:6969/generate/incontext
Content-Type: application/json

{

}

####
POST http://localhost:6969/generate/complete
Content-Type: application/json

{
  "prefix" : "If your mother only knew",
  "temperature" : 0.8
}
####
Content-Type: application/json

{
  "prefix" : "Hi man i just met your mother and"
}
###
POST https://mvsp-api.ncmg.eu/generate/incontext
Content-Type: application/json

{

}
